---
# tasks file for roles/Elk_Monitoring_Ubuntu
- name: adding the gpg ket
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Adding the source
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Updating Ubuntu
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Installing the elastic search
  apt:
    name: elasticsearch
    state: present

- name: Installing kibana
  apt:
    update_cache: yes
    name: kibana
    state: present

- name: Installing logstash
  apt:
    name: logstash
    state: present


