---
# tasks file for roles/Grafana_Monitoring_Ubuntu
- name: Adding the key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add to grafana repo
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: Updating ubuntu
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Installing grafana
  apt:
    name: grafana
    state: present
