prelim_exam: https://github.com/rmsenar-tip/sysad2-12021.git
username: rmsenar-tip

writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"

ftp_debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlsv1=YES\nssl_sslv2=NO\nssl_sslv3=NO"

user: ftpadministrator
ftp_pass: $5$NximQYglwSvaC$JPALFctRxi9u9wjxAlHWb7rwSAggQeKBSE97Vj.dvg.

nag_pass: $5$9cKM0kD0kv.$wT4w7Fbs33XK.YhT5V1JXR0AlLdjHbEAldtQi0RaOD5
admin_pass: rejaycute
